<?php
declare(strict_types=1);

/**
 * @var \ClawRock\Faq\Block\Widget\QuestionList $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \ClawRock\Faq\Api\Data\QuestionInterface $question
 */
$question = $block->getQuestion();
?>
<div class="clawrock-question" id="q-<?= /* @noEscape */ $question->getQuestionId() ?>"
     data-mage-init='{"collapsible":{ "active": false, "animate": 200, "collapsible": true}}'>
    <div data-role="title" class="clawrock-question__title">
        <a href="#" data-role="trigger">
            <span><?= $escaper->escapeHtml($question->getQuestion()) ?></span>
        </a>
    </div>
    <div class="clawrock-question__answer" data-role="content" style="display: none;">
        <?= $escaper->escapeHtml($question->getAnswer()) ?>
    </div>
</div>
