<?php
declare(strict_types=1);

/**
 * @var \ClawRock\Faq\Block\Widget\QuestionList $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \ClawRock\Faq\Api\Data\QuestionInterface $question
 */
$question = $block->getQuestion();
?>
<div class="clawrock-question" id="q-<?= /* @noEscape */ $question->getQuestionId() ?>">
    <div class="clawrock-question__title">
        <h3><?= $escaper->escapeHtml($question->getQuestion()) ?></h3>
    </div>
    <div class="clawrock-question__answer"><?= $escaper->escapeHtml($question->getAnswer()) ?></div>
</div>
